package com.flopster101.siliconplayer

import androidx.compose.foundation.layout.BoxScope
import androidx.compose.runtime.Composable
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.graphics.ImageBitmap
import java.io.File

@Composable
internal fun BoxScope.AppNavigationPlayerOverlaysSection(
    miniPlayerFocusRequester: FocusRequester,
    isPlayerSurfaceVisible: Boolean,
    isPlayerExpanded: Boolean,
    miniExpandPreviewProgress: Float,
    onMiniExpandPreviewProgressChanged: (Float) -> Unit,
    expandFromMiniDrag: Boolean,
    onExpandFromMiniDragChanged: (Boolean) -> Unit,
    collapseFromSwipe: Boolean,
    onCollapseFromSwipeChanged: (Boolean) -> Unit,
    onPlayerExpandedChanged: (Boolean) -> Unit,
    screenHeightPx: Float,
    miniPreviewLiftPx: Float,
    selectedFile: File?,
    visiblePlayableFiles: List<File>,
    isPlaying: Boolean,
    playbackStartInProgress: Boolean,
    seekUiBusy: Boolean,
    durationSeconds: Double,
    positionSeconds: Double,
    metadataTitle: String,
    metadataArtist: String,
    metadataSampleRate: Int,
    metadataChannelCount: Int,
    metadataBitDepthLabel: String,
    decoderName: String?,
    playbackSourceLabel: String?,
    pathOrUrl: String?,
    artworkBitmap: ImageBitmap?,
    activeRepeatMode: RepeatMode,
    playbackCapabilitiesFlags: Int,
    canOpenCurrentCoreSettings: Boolean,
    openCurrentCoreSettings: () -> Unit,
    visualizationMode: VisualizationMode,
    availableVisualizationModes: List<VisualizationMode>,
    cycleVisualizationMode: () -> Unit,
    setVisualizationMode: (VisualizationMode) -> Unit,
    openVisualizationSettings: () -> Unit,
    openSelectedVisualizationSettings: () -> Unit,
    visualizationBarCount: Int,
    visualizationBarSmoothingPercent: Int,
    visualizationBarRoundnessDp: Int,
    visualizationBarOverlayArtwork: Boolean,
    visualizationBarUseThemeColor: Boolean,
    visualizationBarRenderBackend: VisualizationRenderBackend,
    visualizationOscStereo: Boolean,
    visualizationVuAnchor: VisualizationVuAnchor,
    visualizationVuUseThemeColor: Boolean,
    visualizationVuSmoothingPercent: Int,
    visualizationVuRenderBackend: VisualizationRenderBackend,
    visualizationShowDebugInfo: Boolean,
    playerArtworkCornerRadiusDp: Int,
    filenameDisplayMode: FilenameDisplayMode,
    filenameOnlyWhenTitleMissing: Boolean,
    onMiniPlayerExpandRequested: () -> Unit,
    canResumeStoppedTrack: Boolean,
    onHidePlayerSurface: () -> Unit,
    onPreviousTrack: () -> Boolean,
    onNextTrack: () -> Boolean,
    onPlayPause: () -> Unit,
    onPlay: () -> Unit,
    onStopAndClear: () -> Unit,
    onOpenAudioEffects: () -> Unit,
    onPause: () -> Unit,
    canPreviousTrack: Boolean,
    canNextTrack: Boolean,
    onSeek: (Double) -> Unit,
    onPreviousSubtune: () -> Unit,
    onNextSubtune: () -> Unit,
    onOpenSubtuneSelector: () -> Unit,
    canPreviousSubtune: Boolean,
    canNextSubtune: Boolean,
    canOpenSubtuneSelector: Boolean,
    currentSubtuneIndex: Int,
    subtuneCount: Int,
    onCycleRepeatMode: () -> Unit
) {
    MiniPlayerOverlayHost(
        miniPlayerFocusRequester = miniPlayerFocusRequester,
        isPlayerSurfaceVisible = isPlayerSurfaceVisible,
        isPlayerExpanded = isPlayerExpanded,
        miniExpandPreviewProgress = miniExpandPreviewProgress,
        onMiniExpandPreviewProgressChanged = onMiniExpandPreviewProgressChanged,
        expandFromMiniDrag = expandFromMiniDrag,
        onExpandFromMiniDragChanged = onExpandFromMiniDragChanged,
        onCollapseFromSwipeChanged = onCollapseFromSwipeChanged,
        onPlayerExpandedChanged = onPlayerExpandedChanged,
        screenHeightPx = screenHeightPx,
        miniPreviewLiftPx = miniPreviewLiftPx,
        selectedFile = selectedFile,
        visiblePlayableFiles = visiblePlayableFiles,
        isPlaying = isPlaying,
        playbackStartInProgress = playbackStartInProgress,
        seekUiBusy = seekUiBusy,
        durationSeconds = durationSeconds,
        positionSeconds = positionSeconds,
        metadataTitle = metadataTitle,
        metadataArtist = metadataArtist,
        metadataSampleRate = metadataSampleRate,
        metadataChannelCount = metadataChannelCount,
        metadataBitDepthLabel = metadataBitDepthLabel,
        decoderName = decoderName,
        playbackSourceLabel = playbackSourceLabel,
        pathOrUrl = pathOrUrl,
        artworkBitmap = artworkBitmap,
        activeRepeatMode = activeRepeatMode,
        playbackCapabilitiesFlags = playbackCapabilitiesFlags,
        canOpenCurrentCoreSettings = canOpenCurrentCoreSettings,
        openCurrentCoreSettings = openCurrentCoreSettings,
        visualizationMode = visualizationMode,
        availableVisualizationModes = availableVisualizationModes,
        cycleVisualizationMode = cycleVisualizationMode,
        setVisualizationMode = setVisualizationMode,
        openVisualizationSettings = openVisualizationSettings,
        openSelectedVisualizationSettings = openSelectedVisualizationSettings,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        playerArtworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing,
        onMiniPlayerExpandRequested = onMiniPlayerExpandRequested,
        canResumeStoppedTrack = canResumeStoppedTrack,
        onHidePlayerSurface = onHidePlayerSurface,
        onPreviousTrack = { onPreviousTrack() },
        onNextTrack = { onNextTrack() },
        onPlayPause = onPlayPause,
        onStopAndClear = onStopAndClear,
        onOpenAudioEffects = onOpenAudioEffects
    )
    ExpandedPlayerOverlayHost(
        isPlayerSurfaceVisible = isPlayerSurfaceVisible,
        isPlayerExpanded = isPlayerExpanded,
        expandFromMiniDrag = expandFromMiniDrag,
        collapseFromSwipe = collapseFromSwipe,
        onCollapseFromSwipeChanged = onCollapseFromSwipeChanged,
        onMiniExpandPreviewProgressChanged = onMiniExpandPreviewProgressChanged,
        onPlayerExpandedChanged = onPlayerExpandedChanged,
        selectedFile = selectedFile,
        isPlaying = isPlaying,
        playbackStartInProgress = playbackStartInProgress,
        canResumeStoppedTrack = canResumeStoppedTrack,
        onPlay = onPlay,
        onPause = onPause,
        onStopAndClear = onStopAndClear,
        durationSeconds = durationSeconds,
        positionSeconds = positionSeconds,
        canPreviousTrack = canPreviousTrack,
        canNextTrack = canNextTrack,
        title = metadataTitle,
        artist = metadataArtist,
        sampleRateHz = metadataSampleRate,
        channelCount = metadataChannelCount,
        bitDepthLabel = metadataBitDepthLabel,
        decoderName = decoderName,
        playbackSourceLabel = playbackSourceLabel,
        pathOrUrl = pathOrUrl,
        artworkBitmap = artworkBitmap,
        repeatMode = activeRepeatMode,
        playbackCapabilitiesFlags = playbackCapabilitiesFlags,
        seekInProgress = seekUiBusy,
        onSeek = onSeek,
        onPreviousTrack = { onPreviousTrack() },
        onNextTrack = { onNextTrack() },
        onPreviousSubtune = onPreviousSubtune,
        onNextSubtune = onNextSubtune,
        onOpenSubtuneSelector = onOpenSubtuneSelector,
        canPreviousSubtune = canPreviousSubtune,
        canNextSubtune = canNextSubtune,
        canOpenSubtuneSelector = canOpenSubtuneSelector,
        currentSubtuneIndex = currentSubtuneIndex,
        subtuneCount = subtuneCount,
        onCycleRepeatMode = onCycleRepeatMode,
        canOpenCoreSettings = canOpenCurrentCoreSettings,
        onOpenCoreSettings = openCurrentCoreSettings,
        visualizationMode = visualizationMode,
        availableVisualizationModes = availableVisualizationModes,
        onCycleVisualizationMode = cycleVisualizationMode,
        onSelectVisualizationMode = setVisualizationMode,
        onOpenVisualizationSettings = openVisualizationSettings,
        onOpenSelectedVisualizationSettings = openSelectedVisualizationSettings,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        artworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        onOpenAudioEffects = onOpenAudioEffects,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing
    )
}
