package com.flopster101.siliconplayer

import android.content.Context
import android.content.SharedPreferences

internal fun buildSettingsScreenStateFromStateHolders(
    selectedPluginName: String?,
    autoPlayOnTrackSelect: Boolean,
    openPlayerOnTrackSelect: Boolean,
    autoPlayNextTrackOnEnd: Boolean,
    previousRestartsAfterThreshold: Boolean,
    fadePauseResume: Boolean,
    audioFocusInterrupt: Boolean,
    audioDucking: Boolean,
    persistRepeatMode: Boolean,
    themeMode: ThemeMode,
    rememberBrowserLocation: Boolean,
    sortArchivesBeforeFiles: Boolean,
    recentFoldersLimit: Int,
    recentFilesLimit: Int,
    keepScreenOn: Boolean,
    playerArtworkCornerRadiusDp: Int,
    filenameDisplayMode: FilenameDisplayMode,
    filenameOnlyWhenTitleMissing: Boolean,
    unknownTrackDurationSeconds: Int,
    endFadeApplyToAllTracks: Boolean,
    endFadeDurationMs: Int,
    endFadeCurve: EndFadeCurve,
    visualizationMode: VisualizationMode,
    enabledVisualizationModes: Set<VisualizationMode>,
    visualizationShowDebugInfo: Boolean,
    visualizationBarCount: Int,
    visualizationBarSmoothingPercent: Int,
    visualizationBarRoundnessDp: Int,
    visualizationBarOverlayArtwork: Boolean,
    visualizationBarUseThemeColor: Boolean,
    visualizationBarRenderBackend: VisualizationRenderBackend,
    visualizationOscStereo: Boolean,
    visualizationVuAnchor: VisualizationVuAnchor,
    visualizationVuUseThemeColor: Boolean,
    visualizationVuSmoothingPercent: Int,
    visualizationVuRenderBackend: VisualizationRenderBackend,
    ffmpegCapabilities: Int,
    openMptCapabilities: Int,
    vgmPlayCapabilities: Int,
    settingsStates: AppNavigationSettingsStates
): SettingsScreenState {
    return buildSettingsScreenState(
        selectedPluginName = selectedPluginName,
        autoPlayOnTrackSelect = autoPlayOnTrackSelect,
        openPlayerOnTrackSelect = openPlayerOnTrackSelect,
        autoPlayNextTrackOnEnd = autoPlayNextTrackOnEnd,
        previousRestartsAfterThreshold = previousRestartsAfterThreshold,
        fadePauseResume = fadePauseResume,
        respondHeadphoneMediaButtons = settingsStates.respondHeadphoneMediaButtons.value,
        pauseOnHeadphoneDisconnect = settingsStates.pauseOnHeadphoneDisconnect.value,
        audioFocusInterrupt = audioFocusInterrupt,
        audioDucking = audioDucking,
        audioBackendPreference = settingsStates.audioBackendPreference.value,
        audioPerformanceMode = settingsStates.audioPerformanceMode.value,
        audioBufferPreset = settingsStates.audioBufferPreset.value,
        audioResamplerPreference = settingsStates.audioResamplerPreference.value,
        audioAllowBackendFallback = settingsStates.audioAllowBackendFallback.value,
        openPlayerFromNotification = settingsStates.openPlayerFromNotification.value,
        persistRepeatMode = persistRepeatMode,
        themeMode = themeMode,
        rememberBrowserLocation = rememberBrowserLocation,
        sortArchivesBeforeFiles = sortArchivesBeforeFiles,
        recentFoldersLimit = recentFoldersLimit,
        recentFilesLimit = recentFilesLimit,
        urlCacheClearOnLaunch = settingsStates.urlCacheClearOnLaunch.value,
        urlCacheMaxTracks = settingsStates.urlCacheMaxTracks.intValue,
        urlCacheMaxBytes = settingsStates.urlCacheMaxBytes.longValue,
        archiveCacheClearOnLaunch = settingsStates.archiveCacheClearOnLaunch.value,
        archiveCacheMaxMounts = settingsStates.archiveCacheMaxMounts.intValue,
        archiveCacheMaxBytes = settingsStates.archiveCacheMaxBytes.longValue,
        archiveCacheMaxAgeDays = settingsStates.archiveCacheMaxAgeDays.intValue,
        cachedSourceFiles = settingsStates.cachedSourceFiles.value,
        keepScreenOn = keepScreenOn,
        playerArtworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing,
        unknownTrackDurationSeconds = unknownTrackDurationSeconds,
        endFadeApplyToAllTracks = endFadeApplyToAllTracks,
        endFadeDurationMs = endFadeDurationMs,
        endFadeCurve = endFadeCurve,
        visualizationMode = visualizationMode,
        enabledVisualizationModes = enabledVisualizationModes,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        ffmpegSampleRateHz = settingsStates.ffmpegCoreSampleRateHz.intValue,
        ffmpegGaplessRepeatTrack = settingsStates.ffmpegGaplessRepeatTrack.value,
        ffmpegCapabilities = ffmpegCapabilities,
        openMptSampleRateHz = settingsStates.openMptCoreSampleRateHz.intValue,
        openMptCapabilities = openMptCapabilities,
        vgmPlaySampleRateHz = settingsStates.vgmPlayCoreSampleRateHz.intValue,
        vgmPlayCapabilities = vgmPlayCapabilities,
        gmeSampleRateHz = settingsStates.gmeCoreSampleRateHz.intValue,
        sidPlayFpSampleRateHz = settingsStates.sidPlayFpCoreSampleRateHz.intValue,
        lazyUsf2SampleRateHz = settingsStates.lazyUsf2CoreSampleRateHz.intValue,
        lazyUsf2UseHleAudio = settingsStates.lazyUsf2UseHleAudio.value,
        vio2sfInterpolationQuality = settingsStates.vio2sfInterpolationQuality.intValue,
        sidPlayFpBackend = settingsStates.sidPlayFpBackend.intValue,
        sidPlayFpClockMode = settingsStates.sidPlayFpClockMode.intValue,
        sidPlayFpSidModelMode = settingsStates.sidPlayFpSidModelMode.intValue,
        sidPlayFpFilter6581Enabled = settingsStates.sidPlayFpFilter6581Enabled.value,
        sidPlayFpFilter8580Enabled = settingsStates.sidPlayFpFilter8580Enabled.value,
        sidPlayFpDigiBoost8580 = settingsStates.sidPlayFpDigiBoost8580.value,
        sidPlayFpFilterCurve6581Percent = settingsStates.sidPlayFpFilterCurve6581Percent.intValue,
        sidPlayFpFilterRange6581Percent = settingsStates.sidPlayFpFilterRange6581Percent.intValue,
        sidPlayFpFilterCurve8580Percent = settingsStates.sidPlayFpFilterCurve8580Percent.intValue,
        sidPlayFpReSidFpFastSampling = settingsStates.sidPlayFpReSidFpFastSampling.value,
        sidPlayFpReSidFpCombinedWaveformsStrength = settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue,
        gmeTempoPercent = settingsStates.gmeTempoPercent.intValue,
        gmeStereoSeparationPercent = settingsStates.gmeStereoSeparationPercent.intValue,
        gmeEchoEnabled = settingsStates.gmeEchoEnabled.value,
        gmeAccuracyEnabled = settingsStates.gmeAccuracyEnabled.value,
        gmeEqTrebleDecibel = settingsStates.gmeEqTrebleDecibel.intValue,
        gmeEqBassHz = settingsStates.gmeEqBassHz.intValue,
        gmeSpcUseBuiltInFade = settingsStates.gmeSpcUseBuiltInFade.value,
        gmeSpcInterpolation = settingsStates.gmeSpcInterpolation.intValue,
        gmeSpcUseNativeSampleRate = settingsStates.gmeSpcUseNativeSampleRate.value,
        vgmPlayLoopCount = settingsStates.vgmPlayLoopCount.intValue,
        vgmPlayAllowNonLoopingLoop = settingsStates.vgmPlayAllowNonLoopingLoop.value,
        vgmPlayVsyncRate = settingsStates.vgmPlayVsyncRate.intValue,
        vgmPlayResampleMode = settingsStates.vgmPlayResampleMode.intValue,
        vgmPlayChipSampleMode = settingsStates.vgmPlayChipSampleMode.intValue,
        vgmPlayChipSampleRate = settingsStates.vgmPlayChipSampleRate.intValue,
        vgmPlayChipCoreSelections = settingsStates.vgmPlayChipCoreSelections.value,
        openMptStereoSeparationPercent = settingsStates.openMptStereoSeparationPercent.intValue,
        openMptStereoSeparationAmigaPercent = settingsStates.openMptStereoSeparationAmigaPercent.intValue,
        openMptInterpolationFilterLength = settingsStates.openMptInterpolationFilterLength.intValue,
        openMptAmigaResamplerMode = settingsStates.openMptAmigaResamplerMode.intValue,
        openMptAmigaResamplerApplyAllModules = settingsStates.openMptAmigaResamplerApplyAllModules.value,
        openMptVolumeRampingStrength = settingsStates.openMptVolumeRampingStrength.intValue,
        openMptFt2XmVolumeRamping = settingsStates.openMptFt2XmVolumeRamping.value,
        openMptMasterGainMilliBel = settingsStates.openMptMasterGainMilliBel.intValue,
        openMptSurroundEnabled = settingsStates.openMptSurroundEnabled.value
    )
}

internal fun clearAllSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    defaultScopeTextSizeSp: Int,
    selectableVisualizationModes: List<VisualizationMode>,
    onThemeModeChanged: (ThemeMode) -> Unit,
    settingsStates: AppNavigationSettingsStates,
    onAutoPlayOnTrackSelectChanged: (Boolean) -> Unit,
    onOpenPlayerOnTrackSelectChanged: (Boolean) -> Unit,
    onAutoPlayNextTrackOnEndChanged: (Boolean) -> Unit,
    onPreviousRestartsAfterThresholdChanged: (Boolean) -> Unit,
    onFadePauseResumeChanged: (Boolean) -> Unit,
    onPersistRepeatModeChanged: (Boolean) -> Unit,
    onPreferredRepeatModeChanged: (RepeatMode) -> Unit,
    onRememberBrowserLocationChanged: (Boolean) -> Unit,
    onLastBrowserLocationIdChanged: (String?) -> Unit,
    onLastBrowserDirectoryPathChanged: (String?) -> Unit,
    onRecentFoldersLimitChanged: (Int) -> Unit,
    onRecentFilesLimitChanged: (Int) -> Unit,
    onRecentFoldersChanged: (List<RecentPathEntry>) -> Unit,
    onRecentPlayedFilesChanged: (List<RecentPathEntry>) -> Unit,
    onKeepScreenOnChanged: (Boolean) -> Unit,
    onPlayerArtworkCornerRadiusDpChanged: (Int) -> Unit,
    onFilenameDisplayModeChanged: (FilenameDisplayMode) -> Unit,
    onFilenameOnlyWhenTitleMissingChanged: (Boolean) -> Unit,
    onUnknownTrackDurationSecondsChanged: (Int) -> Unit,
    onEndFadeApplyToAllTracksChanged: (Boolean) -> Unit,
    onEndFadeDurationMsChanged: (Int) -> Unit,
    onEndFadeCurveChanged: (EndFadeCurve) -> Unit,
    onVisualizationModeChanged: (VisualizationMode) -> Unit,
    onEnabledVisualizationModesChanged: (Set<VisualizationMode>) -> Unit,
    onVisualizationShowDebugInfoChanged: (Boolean) -> Unit,
    onVisualizationBarCountChanged: (Int) -> Unit,
    onVisualizationBarSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationBarRoundnessDpChanged: (Int) -> Unit,
    onVisualizationBarOverlayArtworkChanged: (Boolean) -> Unit,
    onVisualizationBarUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationBarRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    onVisualizationOscStereoChanged: (Boolean) -> Unit,
    onVisualizationVuAnchorChanged: (VisualizationVuAnchor) -> Unit,
    onVisualizationVuUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationVuSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationVuRenderBackendChanged: (VisualizationRenderBackend) -> Unit
) {
    clearAllSettingsFromMainAction(
        context = context,
        prefs = prefs,
        defaultScopeTextSizeSp = defaultScopeTextSizeSp,
        selectableVisualizationModes = selectableVisualizationModes,
        onThemeModeChanged = onThemeModeChanged,
        ffmpegCoreSampleRateHz = settingsStates.ffmpegCoreSampleRateHz.intValue,
        openMptCoreSampleRateHz = settingsStates.openMptCoreSampleRateHz.intValue,
        vgmPlayCoreSampleRateHz = settingsStates.vgmPlayCoreSampleRateHz.intValue,
        gmeCoreSampleRateHz = settingsStates.gmeCoreSampleRateHz.intValue,
        sidPlayFpCoreSampleRateHz = settingsStates.sidPlayFpCoreSampleRateHz.intValue,
        lazyUsf2CoreSampleRateHz = settingsStates.lazyUsf2CoreSampleRateHz.intValue,
        vio2sfInterpolationQuality = settingsStates.vio2sfInterpolationQuality.intValue,
        vgmPlayLoopCount = settingsStates.vgmPlayLoopCount.intValue,
        vgmPlayVsyncRate = settingsStates.vgmPlayVsyncRate.intValue,
        vgmPlayResampleMode = settingsStates.vgmPlayResampleMode.intValue,
        vgmPlayChipSampleMode = settingsStates.vgmPlayChipSampleMode.intValue,
        vgmPlayChipSampleRate = settingsStates.vgmPlayChipSampleRate.intValue,
        gmeTempoPercent = settingsStates.gmeTempoPercent.intValue,
        gmeStereoSeparationPercent = settingsStates.gmeStereoSeparationPercent.intValue,
        gmeEqTrebleDecibel = settingsStates.gmeEqTrebleDecibel.intValue,
        gmeEqBassHz = settingsStates.gmeEqBassHz.intValue,
        gmeSpcInterpolation = settingsStates.gmeSpcInterpolation.intValue,
        sidPlayFpBackend = settingsStates.sidPlayFpBackend.intValue,
        sidPlayFpClockMode = settingsStates.sidPlayFpClockMode.intValue,
        sidPlayFpSidModelMode = settingsStates.sidPlayFpSidModelMode.intValue,
        sidPlayFpFilterCurve6581Percent = settingsStates.sidPlayFpFilterCurve6581Percent.intValue,
        sidPlayFpFilterRange6581Percent = settingsStates.sidPlayFpFilterRange6581Percent.intValue,
        sidPlayFpFilterCurve8580Percent = settingsStates.sidPlayFpFilterCurve8580Percent.intValue,
        sidPlayFpReSidFpCombinedWaveformsStrength = settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue,
        openMptStereoSeparationPercent = settingsStates.openMptStereoSeparationPercent.intValue,
        openMptStereoSeparationAmigaPercent = settingsStates.openMptStereoSeparationAmigaPercent.intValue,
        openMptInterpolationFilterLength = settingsStates.openMptInterpolationFilterLength.intValue,
        openMptAmigaResamplerMode = settingsStates.openMptAmigaResamplerMode.intValue,
        openMptVolumeRampingStrength = settingsStates.openMptVolumeRampingStrength.intValue,
        openMptMasterGainMilliBel = settingsStates.openMptMasterGainMilliBel.intValue,
        vgmPlayAllowNonLoopingLoop = settingsStates.vgmPlayAllowNonLoopingLoop.value,
        gmeEchoEnabled = settingsStates.gmeEchoEnabled.value,
        gmeAccuracyEnabled = settingsStates.gmeAccuracyEnabled.value,
        gmeSpcUseBuiltInFade = settingsStates.gmeSpcUseBuiltInFade.value,
        gmeSpcUseNativeSampleRate = settingsStates.gmeSpcUseNativeSampleRate.value,
        lazyUsf2UseHleAudio = settingsStates.lazyUsf2UseHleAudio.value,
        sidPlayFpFilter6581Enabled = settingsStates.sidPlayFpFilter6581Enabled.value,
        sidPlayFpFilter8580Enabled = settingsStates.sidPlayFpFilter8580Enabled.value,
        sidPlayFpDigiBoost8580 = settingsStates.sidPlayFpDigiBoost8580.value,
        sidPlayFpReSidFpFastSampling = settingsStates.sidPlayFpReSidFpFastSampling.value,
        openMptAmigaResamplerApplyAllModules = settingsStates.openMptAmigaResamplerApplyAllModules.value,
        openMptFt2XmVolumeRamping = settingsStates.openMptFt2XmVolumeRamping.value,
        openMptSurroundEnabled = settingsStates.openMptSurroundEnabled.value,
        vgmPlayChipCoreSelections = settingsStates.vgmPlayChipCoreSelections.value,
        onAutoPlayOnTrackSelectChanged = onAutoPlayOnTrackSelectChanged,
        onOpenPlayerOnTrackSelectChanged = onOpenPlayerOnTrackSelectChanged,
        onAutoPlayNextTrackOnEndChanged = onAutoPlayNextTrackOnEndChanged,
        onPreviousRestartsAfterThresholdChanged = onPreviousRestartsAfterThresholdChanged,
        onFadePauseResumeChanged = onFadePauseResumeChanged,
        onRespondHeadphoneMediaButtonsChanged = { settingsStates.respondHeadphoneMediaButtons.value = it },
        onPauseOnHeadphoneDisconnectChanged = { settingsStates.pauseOnHeadphoneDisconnect.value = it },
        onAudioBackendPreferenceChanged = { settingsStates.audioBackendPreference.value = it },
        onAudioPerformanceModeChanged = { settingsStates.audioPerformanceMode.value = it },
        onAudioBufferPresetChanged = { settingsStates.audioBufferPreset.value = it },
        onAudioResamplerPreferenceChanged = { settingsStates.audioResamplerPreference.value = it },
        onAudioAllowBackendFallbackChanged = { settingsStates.audioAllowBackendFallback.value = it },
        onOpenPlayerFromNotificationChanged = { settingsStates.openPlayerFromNotification.value = it },
        onPersistRepeatModeChanged = onPersistRepeatModeChanged,
        onPreferredRepeatModeChanged = onPreferredRepeatModeChanged,
        onRememberBrowserLocationChanged = onRememberBrowserLocationChanged,
        onUrlCacheClearOnLaunchChanged = { settingsStates.urlCacheClearOnLaunch.value = it },
        onUrlCacheMaxTracksChanged = { settingsStates.urlCacheMaxTracks.intValue = it },
        onUrlCacheMaxBytesChanged = { settingsStates.urlCacheMaxBytes.longValue = it },
        onArchiveCacheClearOnLaunchChanged = { settingsStates.archiveCacheClearOnLaunch.value = it },
        onArchiveCacheMaxMountsChanged = { settingsStates.archiveCacheMaxMounts.intValue = it },
        onArchiveCacheMaxBytesChanged = { settingsStates.archiveCacheMaxBytes.longValue = it },
        onArchiveCacheMaxAgeDaysChanged = { settingsStates.archiveCacheMaxAgeDays.intValue = it },
        onLastBrowserLocationIdChanged = onLastBrowserLocationIdChanged,
        onLastBrowserDirectoryPathChanged = onLastBrowserDirectoryPathChanged,
        onRecentFoldersLimitChanged = onRecentFoldersLimitChanged,
        onRecentFilesLimitChanged = onRecentFilesLimitChanged,
        onRecentFoldersChanged = onRecentFoldersChanged,
        onRecentPlayedFilesChanged = onRecentPlayedFilesChanged,
        onKeepScreenOnChanged = onKeepScreenOnChanged,
        onPlayerArtworkCornerRadiusDpChanged = onPlayerArtworkCornerRadiusDpChanged,
        onFilenameDisplayModeChanged = onFilenameDisplayModeChanged,
        onFilenameOnlyWhenTitleMissingChanged = onFilenameOnlyWhenTitleMissingChanged,
        onUnknownTrackDurationSecondsChanged = onUnknownTrackDurationSecondsChanged,
        onEndFadeApplyToAllTracksChanged = onEndFadeApplyToAllTracksChanged,
        onEndFadeDurationMsChanged = onEndFadeDurationMsChanged,
        onEndFadeCurveChanged = onEndFadeCurveChanged,
        onVisualizationModeChanged = onVisualizationModeChanged,
        onEnabledVisualizationModesChanged = onEnabledVisualizationModesChanged,
        onVisualizationShowDebugInfoChanged = onVisualizationShowDebugInfoChanged,
        onVisualizationBarCountChanged = onVisualizationBarCountChanged,
        onVisualizationBarSmoothingPercentChanged = onVisualizationBarSmoothingPercentChanged,
        onVisualizationBarRoundnessDpChanged = onVisualizationBarRoundnessDpChanged,
        onVisualizationBarOverlayArtworkChanged = onVisualizationBarOverlayArtworkChanged,
        onVisualizationBarUseThemeColorChanged = onVisualizationBarUseThemeColorChanged,
        onVisualizationBarRenderBackendChanged = onVisualizationBarRenderBackendChanged,
        onVisualizationOscStereoChanged = onVisualizationOscStereoChanged,
        onVisualizationVuAnchorChanged = onVisualizationVuAnchorChanged,
        onVisualizationVuUseThemeColorChanged = onVisualizationVuUseThemeColorChanged,
        onVisualizationVuSmoothingPercentChanged = onVisualizationVuSmoothingPercentChanged,
        onVisualizationVuRenderBackendChanged = onVisualizationVuRenderBackendChanged
    )
}

internal fun clearAllPluginSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    settingsStates: AppNavigationSettingsStates
) {
    clearAllPluginSettingsFromMainAction(
        context = context,
        prefs = prefs,
        onFfmpegCoreSampleRateHzChanged = { settingsStates.ffmpegCoreSampleRateHz.intValue = it },
        onFfmpegGaplessRepeatTrackChanged = { settingsStates.ffmpegGaplessRepeatTrack.value = it },
        onOpenMptCoreSampleRateHzChanged = { settingsStates.openMptCoreSampleRateHz.intValue = it },
        onVgmPlayCoreSampleRateHzChanged = { settingsStates.vgmPlayCoreSampleRateHz.intValue = it },
        onGmeCoreSampleRateHzChanged = { settingsStates.gmeCoreSampleRateHz.intValue = it },
        onSidPlayFpCoreSampleRateHzChanged = { settingsStates.sidPlayFpCoreSampleRateHz.intValue = it },
        onLazyUsf2CoreSampleRateHzChanged = { settingsStates.lazyUsf2CoreSampleRateHz.intValue = it },
        onLazyUsf2UseHleAudioChanged = { settingsStates.lazyUsf2UseHleAudio.value = it },
        onVio2sfInterpolationQualityChanged = { settingsStates.vio2sfInterpolationQuality.intValue = it },
        onSidPlayFpBackendChanged = { settingsStates.sidPlayFpBackend.intValue = it },
        onSidPlayFpClockModeChanged = { settingsStates.sidPlayFpClockMode.intValue = it },
        onSidPlayFpSidModelModeChanged = { settingsStates.sidPlayFpSidModelMode.intValue = it },
        onSidPlayFpFilter6581EnabledChanged = { settingsStates.sidPlayFpFilter6581Enabled.value = it },
        onSidPlayFpFilter8580EnabledChanged = { settingsStates.sidPlayFpFilter8580Enabled.value = it },
        onSidPlayFpDigiBoost8580Changed = { settingsStates.sidPlayFpDigiBoost8580.value = it },
        onSidPlayFpFilterCurve6581PercentChanged = { settingsStates.sidPlayFpFilterCurve6581Percent.intValue = it },
        onSidPlayFpFilterRange6581PercentChanged = { settingsStates.sidPlayFpFilterRange6581Percent.intValue = it },
        onSidPlayFpFilterCurve8580PercentChanged = { settingsStates.sidPlayFpFilterCurve8580Percent.intValue = it },
        onSidPlayFpReSidFpFastSamplingChanged = { settingsStates.sidPlayFpReSidFpFastSampling.value = it },
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = {
            settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue = it
        },
        onGmeTempoPercentChanged = { settingsStates.gmeTempoPercent.intValue = it },
        onGmeStereoSeparationPercentChanged = { settingsStates.gmeStereoSeparationPercent.intValue = it },
        onGmeEchoEnabledChanged = { settingsStates.gmeEchoEnabled.value = it },
        onGmeAccuracyEnabledChanged = { settingsStates.gmeAccuracyEnabled.value = it },
        onGmeEqTrebleDecibelChanged = { settingsStates.gmeEqTrebleDecibel.intValue = it },
        onGmeEqBassHzChanged = { settingsStates.gmeEqBassHz.intValue = it },
        onGmeSpcUseBuiltInFadeChanged = { settingsStates.gmeSpcUseBuiltInFade.value = it },
        onGmeSpcInterpolationChanged = { settingsStates.gmeSpcInterpolation.intValue = it },
        onGmeSpcUseNativeSampleRateChanged = { settingsStates.gmeSpcUseNativeSampleRate.value = it },
        onVgmPlayLoopCountChanged = { settingsStates.vgmPlayLoopCount.intValue = it },
        onVgmPlayAllowNonLoopingLoopChanged = { settingsStates.vgmPlayAllowNonLoopingLoop.value = it },
        onVgmPlayVsyncRateChanged = { settingsStates.vgmPlayVsyncRate.intValue = it },
        onVgmPlayResampleModeChanged = { settingsStates.vgmPlayResampleMode.intValue = it },
        onVgmPlayChipSampleModeChanged = { settingsStates.vgmPlayChipSampleMode.intValue = it },
        onVgmPlayChipSampleRateChanged = { settingsStates.vgmPlayChipSampleRate.intValue = it },
        onVgmPlayChipCoreSelectionsChanged = { settingsStates.vgmPlayChipCoreSelections.value = it },
        onOpenMptStereoSeparationPercentChanged = { settingsStates.openMptStereoSeparationPercent.intValue = it },
        onOpenMptStereoSeparationAmigaPercentChanged = {
            settingsStates.openMptStereoSeparationAmigaPercent.intValue = it
        },
        onOpenMptInterpolationFilterLengthChanged = { settingsStates.openMptInterpolationFilterLength.intValue = it },
        onOpenMptAmigaResamplerModeChanged = { settingsStates.openMptAmigaResamplerMode.intValue = it },
        onOpenMptAmigaResamplerApplyAllModulesChanged = {
            settingsStates.openMptAmigaResamplerApplyAllModules.value = it
        },
        onOpenMptVolumeRampingStrengthChanged = { settingsStates.openMptVolumeRampingStrength.intValue = it },
        onOpenMptFt2XmVolumeRampingChanged = { settingsStates.openMptFt2XmVolumeRamping.value = it },
        onOpenMptMasterGainMilliBelChanged = { settingsStates.openMptMasterGainMilliBel.intValue = it },
        onOpenMptSurroundEnabledChanged = { settingsStates.openMptSurroundEnabled.value = it }
    )
}

internal fun resetPluginSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    pluginName: String,
    settingsStates: AppNavigationSettingsStates
) {
    resetPluginSettingsFromMainAction(
        context = context,
        prefs = prefs,
        pluginName = pluginName,
        onFfmpegCoreSampleRateHzChanged = { settingsStates.ffmpegCoreSampleRateHz.intValue = it },
        onFfmpegGaplessRepeatTrackChanged = { settingsStates.ffmpegGaplessRepeatTrack.value = it },
        onOpenMptCoreSampleRateHzChanged = { settingsStates.openMptCoreSampleRateHz.intValue = it },
        onOpenMptStereoSeparationPercentChanged = { settingsStates.openMptStereoSeparationPercent.intValue = it },
        onOpenMptStereoSeparationAmigaPercentChanged = { settingsStates.openMptStereoSeparationAmigaPercent.intValue = it },
        onOpenMptInterpolationFilterLengthChanged = { settingsStates.openMptInterpolationFilterLength.intValue = it },
        onOpenMptAmigaResamplerModeChanged = { settingsStates.openMptAmigaResamplerMode.intValue = it },
        onOpenMptAmigaResamplerApplyAllModulesChanged = { settingsStates.openMptAmigaResamplerApplyAllModules.value = it },
        onOpenMptVolumeRampingStrengthChanged = { settingsStates.openMptVolumeRampingStrength.intValue = it },
        onOpenMptFt2XmVolumeRampingChanged = { settingsStates.openMptFt2XmVolumeRamping.value = it },
        onOpenMptMasterGainMilliBelChanged = { settingsStates.openMptMasterGainMilliBel.intValue = it },
        onOpenMptSurroundEnabledChanged = { settingsStates.openMptSurroundEnabled.value = it },
        onVgmPlayCoreSampleRateHzChanged = { settingsStates.vgmPlayCoreSampleRateHz.intValue = it },
        onVgmPlayLoopCountChanged = { settingsStates.vgmPlayLoopCount.intValue = it },
        onVgmPlayAllowNonLoopingLoopChanged = { settingsStates.vgmPlayAllowNonLoopingLoop.value = it },
        onVgmPlayVsyncRateChanged = { settingsStates.vgmPlayVsyncRate.intValue = it },
        onVgmPlayResampleModeChanged = { settingsStates.vgmPlayResampleMode.intValue = it },
        onVgmPlayChipSampleModeChanged = { settingsStates.vgmPlayChipSampleMode.intValue = it },
        onVgmPlayChipSampleRateChanged = { settingsStates.vgmPlayChipSampleRate.intValue = it },
        onVgmPlayChipCoreSelectionsChanged = { settingsStates.vgmPlayChipCoreSelections.value = it },
        onGmeCoreSampleRateHzChanged = { settingsStates.gmeCoreSampleRateHz.intValue = it },
        onGmeTempoPercentChanged = { settingsStates.gmeTempoPercent.intValue = it },
        onGmeStereoSeparationPercentChanged = { settingsStates.gmeStereoSeparationPercent.intValue = it },
        onGmeEchoEnabledChanged = { settingsStates.gmeEchoEnabled.value = it },
        onGmeAccuracyEnabledChanged = { settingsStates.gmeAccuracyEnabled.value = it },
        onGmeEqTrebleDecibelChanged = { settingsStates.gmeEqTrebleDecibel.intValue = it },
        onGmeEqBassHzChanged = { settingsStates.gmeEqBassHz.intValue = it },
        onGmeSpcUseBuiltInFadeChanged = { settingsStates.gmeSpcUseBuiltInFade.value = it },
        onGmeSpcInterpolationChanged = { settingsStates.gmeSpcInterpolation.intValue = it },
        onGmeSpcUseNativeSampleRateChanged = { settingsStates.gmeSpcUseNativeSampleRate.value = it },
        onLazyUsf2CoreSampleRateHzChanged = { settingsStates.lazyUsf2CoreSampleRateHz.intValue = it },
        onLazyUsf2UseHleAudioChanged = { settingsStates.lazyUsf2UseHleAudio.value = it },
        onVio2sfInterpolationQualityChanged = { settingsStates.vio2sfInterpolationQuality.intValue = it },
        onSidPlayFpCoreSampleRateHzChanged = { settingsStates.sidPlayFpCoreSampleRateHz.intValue = it },
        onSidPlayFpBackendChanged = { settingsStates.sidPlayFpBackend.intValue = it },
        onSidPlayFpClockModeChanged = { settingsStates.sidPlayFpClockMode.intValue = it },
        onSidPlayFpSidModelModeChanged = { settingsStates.sidPlayFpSidModelMode.intValue = it },
        onSidPlayFpFilter6581EnabledChanged = { settingsStates.sidPlayFpFilter6581Enabled.value = it },
        onSidPlayFpFilter8580EnabledChanged = { settingsStates.sidPlayFpFilter8580Enabled.value = it },
        onSidPlayFpDigiBoost8580Changed = { settingsStates.sidPlayFpDigiBoost8580.value = it },
        onSidPlayFpFilterCurve6581PercentChanged = { settingsStates.sidPlayFpFilterCurve6581Percent.intValue = it },
        onSidPlayFpFilterRange6581PercentChanged = { settingsStates.sidPlayFpFilterRange6581Percent.intValue = it },
        onSidPlayFpFilterCurve8580PercentChanged = { settingsStates.sidPlayFpFilterCurve8580Percent.intValue = it },
        onSidPlayFpReSidFpFastSamplingChanged = { settingsStates.sidPlayFpReSidFpFastSampling.value = it },
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = {
            settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue = it
        }
    )
}
