package com.flopster101.siliconplayer

import android.content.Context
import android.content.SharedPreferences

internal fun clearAllSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    defaultScopeTextSizeSp: Int,
    selectableVisualizationModes: List<VisualizationMode>,
    onThemeModeChanged: (ThemeMode) -> Unit,
    ffmpegCoreSampleRateHz: Int,
    openMptCoreSampleRateHz: Int,
    vgmPlayCoreSampleRateHz: Int,
    gmeCoreSampleRateHz: Int,
    sidPlayFpCoreSampleRateHz: Int,
    lazyUsf2CoreSampleRateHz: Int,
    vgmPlayLoopCount: Int,
    vgmPlayVsyncRate: Int,
    vgmPlayResampleMode: Int,
    vgmPlayChipSampleMode: Int,
    vgmPlayChipSampleRate: Int,
    gmeTempoPercent: Int,
    gmeStereoSeparationPercent: Int,
    gmeEqTrebleDecibel: Int,
    gmeEqBassHz: Int,
    gmeSpcInterpolation: Int,
    sidPlayFpBackend: Int,
    sidPlayFpClockMode: Int,
    sidPlayFpSidModelMode: Int,
    sidPlayFpFilterCurve6581Percent: Int,
    sidPlayFpFilterRange6581Percent: Int,
    sidPlayFpFilterCurve8580Percent: Int,
    sidPlayFpReSidFpCombinedWaveformsStrength: Int,
    openMptStereoSeparationPercent: Int,
    openMptStereoSeparationAmigaPercent: Int,
    openMptInterpolationFilterLength: Int,
    openMptAmigaResamplerMode: Int,
    openMptVolumeRampingStrength: Int,
    openMptMasterGainMilliBel: Int,
    vgmPlayAllowNonLoopingLoop: Boolean,
    gmeEchoEnabled: Boolean,
    gmeAccuracyEnabled: Boolean,
    gmeSpcUseBuiltInFade: Boolean,
    gmeSpcUseNativeSampleRate: Boolean,
    lazyUsf2UseHleAudio: Boolean,
    sidPlayFpFilter6581Enabled: Boolean,
    sidPlayFpFilter8580Enabled: Boolean,
    sidPlayFpDigiBoost8580: Boolean,
    sidPlayFpReSidFpFastSampling: Boolean,
    openMptAmigaResamplerApplyAllModules: Boolean,
    openMptFt2XmVolumeRamping: Boolean,
    openMptSurroundEnabled: Boolean,
    vgmPlayChipCoreSelections: Map<String, Int>,
    onAutoPlayOnTrackSelectChanged: (Boolean) -> Unit,
    onOpenPlayerOnTrackSelectChanged: (Boolean) -> Unit,
    onAutoPlayNextTrackOnEndChanged: (Boolean) -> Unit,
    onPreviousRestartsAfterThresholdChanged: (Boolean) -> Unit,
    onRespondHeadphoneMediaButtonsChanged: (Boolean) -> Unit,
    onPauseOnHeadphoneDisconnectChanged: (Boolean) -> Unit,
    onAudioBackendPreferenceChanged: (AudioBackendPreference) -> Unit,
    onAudioPerformanceModeChanged: (AudioPerformanceMode) -> Unit,
    onAudioBufferPresetChanged: (AudioBufferPreset) -> Unit,
    onAudioResamplerPreferenceChanged: (AudioResamplerPreference) -> Unit,
    onAudioAllowBackendFallbackChanged: (Boolean) -> Unit,
    onOpenPlayerFromNotificationChanged: (Boolean) -> Unit,
    onPersistRepeatModeChanged: (Boolean) -> Unit,
    onPreferredRepeatModeChanged: (RepeatMode) -> Unit,
    onRememberBrowserLocationChanged: (Boolean) -> Unit,
    onUrlCacheClearOnLaunchChanged: (Boolean) -> Unit,
    onUrlCacheMaxTracksChanged: (Int) -> Unit,
    onUrlCacheMaxBytesChanged: (Long) -> Unit,
    onLastBrowserLocationIdChanged: (String?) -> Unit,
    onLastBrowserDirectoryPathChanged: (String?) -> Unit,
    onRecentFoldersLimitChanged: (Int) -> Unit,
    onRecentFilesLimitChanged: (Int) -> Unit,
    onRecentFoldersChanged: (List<RecentPathEntry>) -> Unit,
    onRecentPlayedFilesChanged: (List<RecentPathEntry>) -> Unit,
    onKeepScreenOnChanged: (Boolean) -> Unit,
    onPlayerArtworkCornerRadiusDpChanged: (Int) -> Unit,
    onFilenameDisplayModeChanged: (FilenameDisplayMode) -> Unit,
    onFilenameOnlyWhenTitleMissingChanged: (Boolean) -> Unit,
    onUnknownTrackDurationSecondsChanged: (Int) -> Unit,
    onEndFadeApplyToAllTracksChanged: (Boolean) -> Unit,
    onEndFadeDurationMsChanged: (Int) -> Unit,
    onEndFadeCurveChanged: (EndFadeCurve) -> Unit,
    onVisualizationModeChanged: (VisualizationMode) -> Unit,
    onEnabledVisualizationModesChanged: (Set<VisualizationMode>) -> Unit,
    onVisualizationShowDebugInfoChanged: (Boolean) -> Unit,
    onVisualizationBarCountChanged: (Int) -> Unit,
    onVisualizationBarSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationBarRoundnessDpChanged: (Int) -> Unit,
    onVisualizationBarOverlayArtworkChanged: (Boolean) -> Unit,
    onVisualizationBarUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationBarRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    onVisualizationOscStereoChanged: (Boolean) -> Unit,
    onVisualizationVuAnchorChanged: (VisualizationVuAnchor) -> Unit,
    onVisualizationVuUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationVuSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationVuRenderBackendChanged: (VisualizationRenderBackend) -> Unit
) {
    clearAllSettingsAction(
        context = context,
        prefs = prefs,
        defaultScopeTextSizeSp = defaultScopeTextSizeSp,
        selectableVisualizationModes = selectableVisualizationModes,
        onThemeModeChanged = onThemeModeChanged,
        ffmpegCoreSampleRateHz = ffmpegCoreSampleRateHz,
        openMptCoreSampleRateHz = openMptCoreSampleRateHz,
        vgmPlayCoreSampleRateHz = vgmPlayCoreSampleRateHz,
        gmeCoreSampleRateHz = gmeCoreSampleRateHz,
        sidPlayFpCoreSampleRateHz = sidPlayFpCoreSampleRateHz,
        lazyUsf2CoreSampleRateHz = lazyUsf2CoreSampleRateHz,
        vgmPlayLoopCount = vgmPlayLoopCount,
        vgmPlayVsyncRate = vgmPlayVsyncRate,
        vgmPlayResampleMode = vgmPlayResampleMode,
        vgmPlayChipSampleMode = vgmPlayChipSampleMode,
        vgmPlayChipSampleRate = vgmPlayChipSampleRate,
        gmeTempoPercent = gmeTempoPercent,
        gmeStereoSeparationPercent = gmeStereoSeparationPercent,
        gmeEqTrebleDecibel = gmeEqTrebleDecibel,
        gmeEqBassHz = gmeEqBassHz,
        gmeSpcInterpolation = gmeSpcInterpolation,
        sidPlayFpBackend = sidPlayFpBackend,
        sidPlayFpClockMode = sidPlayFpClockMode,
        sidPlayFpSidModelMode = sidPlayFpSidModelMode,
        sidPlayFpFilterCurve6581Percent = sidPlayFpFilterCurve6581Percent,
        sidPlayFpFilterRange6581Percent = sidPlayFpFilterRange6581Percent,
        sidPlayFpFilterCurve8580Percent = sidPlayFpFilterCurve8580Percent,
        sidPlayFpReSidFpCombinedWaveformsStrength = sidPlayFpReSidFpCombinedWaveformsStrength,
        openMptStereoSeparationPercent = openMptStereoSeparationPercent,
        openMptStereoSeparationAmigaPercent = openMptStereoSeparationAmigaPercent,
        openMptInterpolationFilterLength = openMptInterpolationFilterLength,
        openMptAmigaResamplerMode = openMptAmigaResamplerMode,
        openMptVolumeRampingStrength = openMptVolumeRampingStrength,
        openMptMasterGainMilliBel = openMptMasterGainMilliBel,
        vgmPlayAllowNonLoopingLoop = vgmPlayAllowNonLoopingLoop,
        gmeEchoEnabled = gmeEchoEnabled,
        gmeAccuracyEnabled = gmeAccuracyEnabled,
        gmeSpcUseBuiltInFade = gmeSpcUseBuiltInFade,
        gmeSpcUseNativeSampleRate = gmeSpcUseNativeSampleRate,
        lazyUsf2UseHleAudio = lazyUsf2UseHleAudio,
        sidPlayFpFilter6581Enabled = sidPlayFpFilter6581Enabled,
        sidPlayFpFilter8580Enabled = sidPlayFpFilter8580Enabled,
        sidPlayFpDigiBoost8580 = sidPlayFpDigiBoost8580,
        sidPlayFpReSidFpFastSampling = sidPlayFpReSidFpFastSampling,
        openMptAmigaResamplerApplyAllModules = openMptAmigaResamplerApplyAllModules,
        openMptFt2XmVolumeRamping = openMptFt2XmVolumeRamping,
        openMptSurroundEnabled = openMptSurroundEnabled,
        vgmPlayChipCoreSelections = vgmPlayChipCoreSelections,
        onAutoPlayOnTrackSelectChanged = onAutoPlayOnTrackSelectChanged,
        onOpenPlayerOnTrackSelectChanged = onOpenPlayerOnTrackSelectChanged,
        onAutoPlayNextTrackOnEndChanged = onAutoPlayNextTrackOnEndChanged,
        onPreviousRestartsAfterThresholdChanged = onPreviousRestartsAfterThresholdChanged,
        onRespondHeadphoneMediaButtonsChanged = onRespondHeadphoneMediaButtonsChanged,
        onPauseOnHeadphoneDisconnectChanged = onPauseOnHeadphoneDisconnectChanged,
        onAudioBackendPreferenceChanged = onAudioBackendPreferenceChanged,
        onAudioPerformanceModeChanged = onAudioPerformanceModeChanged,
        onAudioBufferPresetChanged = onAudioBufferPresetChanged,
        onAudioResamplerPreferenceChanged = onAudioResamplerPreferenceChanged,
        onAudioAllowBackendFallbackChanged = onAudioAllowBackendFallbackChanged,
        onOpenPlayerFromNotificationChanged = onOpenPlayerFromNotificationChanged,
        onPersistRepeatModeChanged = onPersistRepeatModeChanged,
        onPreferredRepeatModeChanged = onPreferredRepeatModeChanged,
        onRememberBrowserLocationChanged = onRememberBrowserLocationChanged,
        onUrlCacheClearOnLaunchChanged = onUrlCacheClearOnLaunchChanged,
        onUrlCacheMaxTracksChanged = onUrlCacheMaxTracksChanged,
        onUrlCacheMaxBytesChanged = onUrlCacheMaxBytesChanged,
        onLastBrowserLocationIdChanged = onLastBrowserLocationIdChanged,
        onLastBrowserDirectoryPathChanged = onLastBrowserDirectoryPathChanged,
        onRecentFoldersLimitChanged = onRecentFoldersLimitChanged,
        onRecentFilesLimitChanged = onRecentFilesLimitChanged,
        onRecentFoldersChanged = onRecentFoldersChanged,
        onRecentPlayedFilesChanged = onRecentPlayedFilesChanged,
        onKeepScreenOnChanged = onKeepScreenOnChanged,
        onPlayerArtworkCornerRadiusDpChanged = onPlayerArtworkCornerRadiusDpChanged,
        onFilenameDisplayModeChanged = onFilenameDisplayModeChanged,
        onFilenameOnlyWhenTitleMissingChanged = onFilenameOnlyWhenTitleMissingChanged,
        onUnknownTrackDurationSecondsChanged = onUnknownTrackDurationSecondsChanged,
        onEndFadeApplyToAllTracksChanged = onEndFadeApplyToAllTracksChanged,
        onEndFadeDurationMsChanged = onEndFadeDurationMsChanged,
        onEndFadeCurveChanged = onEndFadeCurveChanged,
        onVisualizationModeChanged = onVisualizationModeChanged,
        onEnabledVisualizationModesChanged = onEnabledVisualizationModesChanged,
        onVisualizationShowDebugInfoChanged = onVisualizationShowDebugInfoChanged,
        onVisualizationBarCountChanged = onVisualizationBarCountChanged,
        onVisualizationBarSmoothingPercentChanged = onVisualizationBarSmoothingPercentChanged,
        onVisualizationBarRoundnessDpChanged = onVisualizationBarRoundnessDpChanged,
        onVisualizationBarOverlayArtworkChanged = onVisualizationBarOverlayArtworkChanged,
        onVisualizationBarUseThemeColorChanged = onVisualizationBarUseThemeColorChanged,
        onVisualizationBarRenderBackendChanged = onVisualizationBarRenderBackendChanged,
        onVisualizationOscStereoChanged = onVisualizationOscStereoChanged,
        onVisualizationVuAnchorChanged = onVisualizationVuAnchorChanged,
        onVisualizationVuUseThemeColorChanged = onVisualizationVuUseThemeColorChanged,
        onVisualizationVuSmoothingPercentChanged = onVisualizationVuSmoothingPercentChanged,
        onVisualizationVuRenderBackendChanged = onVisualizationVuRenderBackendChanged
    )
}

internal fun clearAllPluginSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    onFfmpegCoreSampleRateHzChanged: (Int) -> Unit,
    onOpenMptCoreSampleRateHzChanged: (Int) -> Unit,
    onVgmPlayCoreSampleRateHzChanged: (Int) -> Unit,
    onGmeCoreSampleRateHzChanged: (Int) -> Unit,
    onSidPlayFpCoreSampleRateHzChanged: (Int) -> Unit,
    onLazyUsf2CoreSampleRateHzChanged: (Int) -> Unit,
    onLazyUsf2UseHleAudioChanged: (Boolean) -> Unit,
    onSidPlayFpBackendChanged: (Int) -> Unit,
    onSidPlayFpClockModeChanged: (Int) -> Unit,
    onSidPlayFpSidModelModeChanged: (Int) -> Unit,
    onSidPlayFpFilter6581EnabledChanged: (Boolean) -> Unit,
    onSidPlayFpFilter8580EnabledChanged: (Boolean) -> Unit,
    onSidPlayFpDigiBoost8580Changed: (Boolean) -> Unit,
    onSidPlayFpFilterCurve6581PercentChanged: (Int) -> Unit,
    onSidPlayFpFilterRange6581PercentChanged: (Int) -> Unit,
    onSidPlayFpFilterCurve8580PercentChanged: (Int) -> Unit,
    onSidPlayFpReSidFpFastSamplingChanged: (Boolean) -> Unit,
    onSidPlayFpReSidFpCombinedWaveformsStrengthChanged: (Int) -> Unit,
    onGmeTempoPercentChanged: (Int) -> Unit,
    onGmeStereoSeparationPercentChanged: (Int) -> Unit,
    onGmeEchoEnabledChanged: (Boolean) -> Unit,
    onGmeAccuracyEnabledChanged: (Boolean) -> Unit,
    onGmeEqTrebleDecibelChanged: (Int) -> Unit,
    onGmeEqBassHzChanged: (Int) -> Unit,
    onGmeSpcUseBuiltInFadeChanged: (Boolean) -> Unit,
    onGmeSpcInterpolationChanged: (Int) -> Unit,
    onGmeSpcUseNativeSampleRateChanged: (Boolean) -> Unit,
    onVgmPlayLoopCountChanged: (Int) -> Unit,
    onVgmPlayAllowNonLoopingLoopChanged: (Boolean) -> Unit,
    onVgmPlayVsyncRateChanged: (Int) -> Unit,
    onVgmPlayResampleModeChanged: (Int) -> Unit,
    onVgmPlayChipSampleModeChanged: (Int) -> Unit,
    onVgmPlayChipSampleRateChanged: (Int) -> Unit,
    onVgmPlayChipCoreSelectionsChanged: (Map<String, Int>) -> Unit,
    onOpenMptStereoSeparationPercentChanged: (Int) -> Unit,
    onOpenMptStereoSeparationAmigaPercentChanged: (Int) -> Unit,
    onOpenMptInterpolationFilterLengthChanged: (Int) -> Unit,
    onOpenMptAmigaResamplerModeChanged: (Int) -> Unit,
    onOpenMptAmigaResamplerApplyAllModulesChanged: (Boolean) -> Unit,
    onOpenMptVolumeRampingStrengthChanged: (Int) -> Unit,
    onOpenMptFt2XmVolumeRampingChanged: (Boolean) -> Unit,
    onOpenMptMasterGainMilliBelChanged: (Int) -> Unit,
    onOpenMptSurroundEnabledChanged: (Boolean) -> Unit
) {
    clearAllPluginSettingsAction(
        context = context,
        prefs = prefs,
        onFfmpegCoreSampleRateHzChanged = onFfmpegCoreSampleRateHzChanged,
        onOpenMptCoreSampleRateHzChanged = onOpenMptCoreSampleRateHzChanged,
        onVgmPlayCoreSampleRateHzChanged = onVgmPlayCoreSampleRateHzChanged,
        onGmeCoreSampleRateHzChanged = onGmeCoreSampleRateHzChanged,
        onSidPlayFpCoreSampleRateHzChanged = onSidPlayFpCoreSampleRateHzChanged,
        onLazyUsf2CoreSampleRateHzChanged = onLazyUsf2CoreSampleRateHzChanged,
        onLazyUsf2UseHleAudioChanged = onLazyUsf2UseHleAudioChanged,
        onSidPlayFpBackendChanged = onSidPlayFpBackendChanged,
        onSidPlayFpClockModeChanged = onSidPlayFpClockModeChanged,
        onSidPlayFpSidModelModeChanged = onSidPlayFpSidModelModeChanged,
        onSidPlayFpFilter6581EnabledChanged = onSidPlayFpFilter6581EnabledChanged,
        onSidPlayFpFilter8580EnabledChanged = onSidPlayFpFilter8580EnabledChanged,
        onSidPlayFpDigiBoost8580Changed = onSidPlayFpDigiBoost8580Changed,
        onSidPlayFpFilterCurve6581PercentChanged = onSidPlayFpFilterCurve6581PercentChanged,
        onSidPlayFpFilterRange6581PercentChanged = onSidPlayFpFilterRange6581PercentChanged,
        onSidPlayFpFilterCurve8580PercentChanged = onSidPlayFpFilterCurve8580PercentChanged,
        onSidPlayFpReSidFpFastSamplingChanged = onSidPlayFpReSidFpFastSamplingChanged,
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = onSidPlayFpReSidFpCombinedWaveformsStrengthChanged,
        onGmeTempoPercentChanged = onGmeTempoPercentChanged,
        onGmeStereoSeparationPercentChanged = onGmeStereoSeparationPercentChanged,
        onGmeEchoEnabledChanged = onGmeEchoEnabledChanged,
        onGmeAccuracyEnabledChanged = onGmeAccuracyEnabledChanged,
        onGmeEqTrebleDecibelChanged = onGmeEqTrebleDecibelChanged,
        onGmeEqBassHzChanged = onGmeEqBassHzChanged,
        onGmeSpcUseBuiltInFadeChanged = onGmeSpcUseBuiltInFadeChanged,
        onGmeSpcInterpolationChanged = onGmeSpcInterpolationChanged,
        onGmeSpcUseNativeSampleRateChanged = onGmeSpcUseNativeSampleRateChanged,
        onVgmPlayLoopCountChanged = onVgmPlayLoopCountChanged,
        onVgmPlayAllowNonLoopingLoopChanged = onVgmPlayAllowNonLoopingLoopChanged,
        onVgmPlayVsyncRateChanged = onVgmPlayVsyncRateChanged,
        onVgmPlayResampleModeChanged = onVgmPlayResampleModeChanged,
        onVgmPlayChipSampleModeChanged = onVgmPlayChipSampleModeChanged,
        onVgmPlayChipSampleRateChanged = onVgmPlayChipSampleRateChanged,
        onVgmPlayChipCoreSelectionsChanged = onVgmPlayChipCoreSelectionsChanged,
        onOpenMptStereoSeparationPercentChanged = onOpenMptStereoSeparationPercentChanged,
        onOpenMptStereoSeparationAmigaPercentChanged = onOpenMptStereoSeparationAmigaPercentChanged,
        onOpenMptInterpolationFilterLengthChanged = onOpenMptInterpolationFilterLengthChanged,
        onOpenMptAmigaResamplerModeChanged = onOpenMptAmigaResamplerModeChanged,
        onOpenMptAmigaResamplerApplyAllModulesChanged = onOpenMptAmigaResamplerApplyAllModulesChanged,
        onOpenMptVolumeRampingStrengthChanged = onOpenMptVolumeRampingStrengthChanged,
        onOpenMptFt2XmVolumeRampingChanged = onOpenMptFt2XmVolumeRampingChanged,
        onOpenMptMasterGainMilliBelChanged = onOpenMptMasterGainMilliBelChanged,
        onOpenMptSurroundEnabledChanged = onOpenMptSurroundEnabledChanged
    )
}

internal fun resetPluginSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    pluginName: String,
    onFfmpegCoreSampleRateHzChanged: (Int) -> Unit,
    onOpenMptCoreSampleRateHzChanged: (Int) -> Unit,
    onOpenMptStereoSeparationPercentChanged: (Int) -> Unit,
    onOpenMptStereoSeparationAmigaPercentChanged: (Int) -> Unit,
    onOpenMptInterpolationFilterLengthChanged: (Int) -> Unit,
    onOpenMptAmigaResamplerModeChanged: (Int) -> Unit,
    onOpenMptAmigaResamplerApplyAllModulesChanged: (Boolean) -> Unit,
    onOpenMptVolumeRampingStrengthChanged: (Int) -> Unit,
    onOpenMptFt2XmVolumeRampingChanged: (Boolean) -> Unit,
    onOpenMptMasterGainMilliBelChanged: (Int) -> Unit,
    onOpenMptSurroundEnabledChanged: (Boolean) -> Unit,
    onVgmPlayCoreSampleRateHzChanged: (Int) -> Unit,
    onVgmPlayLoopCountChanged: (Int) -> Unit,
    onVgmPlayAllowNonLoopingLoopChanged: (Boolean) -> Unit,
    onVgmPlayVsyncRateChanged: (Int) -> Unit,
    onVgmPlayResampleModeChanged: (Int) -> Unit,
    onVgmPlayChipSampleModeChanged: (Int) -> Unit,
    onVgmPlayChipSampleRateChanged: (Int) -> Unit,
    onVgmPlayChipCoreSelectionsChanged: (Map<String, Int>) -> Unit,
    onGmeCoreSampleRateHzChanged: (Int) -> Unit,
    onGmeTempoPercentChanged: (Int) -> Unit,
    onGmeStereoSeparationPercentChanged: (Int) -> Unit,
    onGmeEchoEnabledChanged: (Boolean) -> Unit,
    onGmeAccuracyEnabledChanged: (Boolean) -> Unit,
    onGmeEqTrebleDecibelChanged: (Int) -> Unit,
    onGmeEqBassHzChanged: (Int) -> Unit,
    onGmeSpcUseBuiltInFadeChanged: (Boolean) -> Unit,
    onGmeSpcInterpolationChanged: (Int) -> Unit,
    onGmeSpcUseNativeSampleRateChanged: (Boolean) -> Unit,
    onLazyUsf2CoreSampleRateHzChanged: (Int) -> Unit,
    onLazyUsf2UseHleAudioChanged: (Boolean) -> Unit,
    onSidPlayFpCoreSampleRateHzChanged: (Int) -> Unit,
    onSidPlayFpBackendChanged: (Int) -> Unit,
    onSidPlayFpClockModeChanged: (Int) -> Unit,
    onSidPlayFpSidModelModeChanged: (Int) -> Unit,
    onSidPlayFpFilter6581EnabledChanged: (Boolean) -> Unit,
    onSidPlayFpFilter8580EnabledChanged: (Boolean) -> Unit,
    onSidPlayFpDigiBoost8580Changed: (Boolean) -> Unit,
    onSidPlayFpFilterCurve6581PercentChanged: (Int) -> Unit,
    onSidPlayFpFilterRange6581PercentChanged: (Int) -> Unit,
    onSidPlayFpFilterCurve8580PercentChanged: (Int) -> Unit,
    onSidPlayFpReSidFpFastSamplingChanged: (Boolean) -> Unit,
    onSidPlayFpReSidFpCombinedWaveformsStrengthChanged: (Int) -> Unit
) {
    resetPluginSettingsAction(
        context = context,
        prefs = prefs,
        pluginName = pluginName,
        onFfmpegCoreSampleRateHzChanged = onFfmpegCoreSampleRateHzChanged,
        onOpenMptCoreSampleRateHzChanged = onOpenMptCoreSampleRateHzChanged,
        onOpenMptStereoSeparationPercentChanged = onOpenMptStereoSeparationPercentChanged,
        onOpenMptStereoSeparationAmigaPercentChanged = onOpenMptStereoSeparationAmigaPercentChanged,
        onOpenMptInterpolationFilterLengthChanged = onOpenMptInterpolationFilterLengthChanged,
        onOpenMptAmigaResamplerModeChanged = onOpenMptAmigaResamplerModeChanged,
        onOpenMptAmigaResamplerApplyAllModulesChanged = onOpenMptAmigaResamplerApplyAllModulesChanged,
        onOpenMptVolumeRampingStrengthChanged = onOpenMptVolumeRampingStrengthChanged,
        onOpenMptFt2XmVolumeRampingChanged = onOpenMptFt2XmVolumeRampingChanged,
        onOpenMptMasterGainMilliBelChanged = onOpenMptMasterGainMilliBelChanged,
        onOpenMptSurroundEnabledChanged = onOpenMptSurroundEnabledChanged,
        onVgmPlayCoreSampleRateHzChanged = onVgmPlayCoreSampleRateHzChanged,
        onVgmPlayLoopCountChanged = onVgmPlayLoopCountChanged,
        onVgmPlayAllowNonLoopingLoopChanged = onVgmPlayAllowNonLoopingLoopChanged,
        onVgmPlayVsyncRateChanged = onVgmPlayVsyncRateChanged,
        onVgmPlayResampleModeChanged = onVgmPlayResampleModeChanged,
        onVgmPlayChipSampleModeChanged = onVgmPlayChipSampleModeChanged,
        onVgmPlayChipSampleRateChanged = onVgmPlayChipSampleRateChanged,
        onVgmPlayChipCoreSelectionsChanged = onVgmPlayChipCoreSelectionsChanged,
        onGmeCoreSampleRateHzChanged = onGmeCoreSampleRateHzChanged,
        onGmeTempoPercentChanged = onGmeTempoPercentChanged,
        onGmeStereoSeparationPercentChanged = onGmeStereoSeparationPercentChanged,
        onGmeEchoEnabledChanged = onGmeEchoEnabledChanged,
        onGmeAccuracyEnabledChanged = onGmeAccuracyEnabledChanged,
        onGmeEqTrebleDecibelChanged = onGmeEqTrebleDecibelChanged,
        onGmeEqBassHzChanged = onGmeEqBassHzChanged,
        onGmeSpcUseBuiltInFadeChanged = onGmeSpcUseBuiltInFadeChanged,
        onGmeSpcInterpolationChanged = onGmeSpcInterpolationChanged,
        onGmeSpcUseNativeSampleRateChanged = onGmeSpcUseNativeSampleRateChanged,
        onLazyUsf2CoreSampleRateHzChanged = onLazyUsf2CoreSampleRateHzChanged,
        onLazyUsf2UseHleAudioChanged = onLazyUsf2UseHleAudioChanged,
        onSidPlayFpCoreSampleRateHzChanged = onSidPlayFpCoreSampleRateHzChanged,
        onSidPlayFpBackendChanged = onSidPlayFpBackendChanged,
        onSidPlayFpClockModeChanged = onSidPlayFpClockModeChanged,
        onSidPlayFpSidModelModeChanged = onSidPlayFpSidModelModeChanged,
        onSidPlayFpFilter6581EnabledChanged = onSidPlayFpFilter6581EnabledChanged,
        onSidPlayFpFilter8580EnabledChanged = onSidPlayFpFilter8580EnabledChanged,
        onSidPlayFpDigiBoost8580Changed = onSidPlayFpDigiBoost8580Changed,
        onSidPlayFpFilterCurve6581PercentChanged = onSidPlayFpFilterCurve6581PercentChanged,
        onSidPlayFpFilterRange6581PercentChanged = onSidPlayFpFilterRange6581PercentChanged,
        onSidPlayFpFilterCurve8580PercentChanged = onSidPlayFpFilterCurve8580PercentChanged,
        onSidPlayFpReSidFpFastSamplingChanged = onSidPlayFpReSidFpFastSamplingChanged,
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = onSidPlayFpReSidFpCombinedWaveformsStrengthChanged
    )
}
