package com.flopster101.siliconplayer

internal fun buildSettingsScreenState(
    selectedPluginName: String?,
    autoPlayOnTrackSelect: Boolean,
    openPlayerOnTrackSelect: Boolean,
    autoPlayNextTrackOnEnd: Boolean,
    previousRestartsAfterThreshold: Boolean,
    respondHeadphoneMediaButtons: Boolean,
    pauseOnHeadphoneDisconnect: Boolean,
    audioFocusInterrupt: Boolean,
    audioDucking: Boolean,
    audioBackendPreference: AudioBackendPreference,
    audioPerformanceMode: AudioPerformanceMode,
    audioBufferPreset: AudioBufferPreset,
    audioResamplerPreference: AudioResamplerPreference,
    audioAllowBackendFallback: Boolean,
    openPlayerFromNotification: Boolean,
    persistRepeatMode: Boolean,
    themeMode: ThemeMode,
    rememberBrowserLocation: Boolean,
    recentFoldersLimit: Int,
    recentFilesLimit: Int,
    urlCacheClearOnLaunch: Boolean,
    urlCacheMaxTracks: Int,
    urlCacheMaxBytes: Long,
    cachedSourceFiles: List<CachedSourceFile>,
    keepScreenOn: Boolean,
    playerArtworkCornerRadiusDp: Int,
    filenameDisplayMode: FilenameDisplayMode,
    filenameOnlyWhenTitleMissing: Boolean,
    unknownTrackDurationSeconds: Int,
    endFadeApplyToAllTracks: Boolean,
    endFadeDurationMs: Int,
    endFadeCurve: EndFadeCurve,
    visualizationMode: VisualizationMode,
    enabledVisualizationModes: Set<VisualizationMode>,
    visualizationShowDebugInfo: Boolean,
    visualizationBarCount: Int,
    visualizationBarSmoothingPercent: Int,
    visualizationBarRoundnessDp: Int,
    visualizationBarOverlayArtwork: Boolean,
    visualizationBarUseThemeColor: Boolean,
    visualizationBarRenderBackend: VisualizationRenderBackend,
    visualizationOscStereo: Boolean,
    visualizationVuAnchor: VisualizationVuAnchor,
    visualizationVuUseThemeColor: Boolean,
    visualizationVuSmoothingPercent: Int,
    visualizationVuRenderBackend: VisualizationRenderBackend,
    ffmpegSampleRateHz: Int,
    ffmpegCapabilities: Int,
    openMptSampleRateHz: Int,
    openMptCapabilities: Int,
    vgmPlaySampleRateHz: Int,
    vgmPlayCapabilities: Int,
    gmeSampleRateHz: Int,
    sidPlayFpSampleRateHz: Int,
    lazyUsf2SampleRateHz: Int,
    lazyUsf2UseHleAudio: Boolean,
    sidPlayFpBackend: Int,
    sidPlayFpClockMode: Int,
    sidPlayFpSidModelMode: Int,
    sidPlayFpFilter6581Enabled: Boolean,
    sidPlayFpFilter8580Enabled: Boolean,
    sidPlayFpDigiBoost8580: Boolean,
    sidPlayFpFilterCurve6581Percent: Int,
    sidPlayFpFilterRange6581Percent: Int,
    sidPlayFpFilterCurve8580Percent: Int,
    sidPlayFpReSidFpFastSampling: Boolean,
    sidPlayFpReSidFpCombinedWaveformsStrength: Int,
    gmeTempoPercent: Int,
    gmeStereoSeparationPercent: Int,
    gmeEchoEnabled: Boolean,
    gmeAccuracyEnabled: Boolean,
    gmeEqTrebleDecibel: Int,
    gmeEqBassHz: Int,
    gmeSpcUseBuiltInFade: Boolean,
    gmeSpcInterpolation: Int,
    gmeSpcUseNativeSampleRate: Boolean,
    vgmPlayLoopCount: Int,
    vgmPlayAllowNonLoopingLoop: Boolean,
    vgmPlayVsyncRate: Int,
    vgmPlayResampleMode: Int,
    vgmPlayChipSampleMode: Int,
    vgmPlayChipSampleRate: Int,
    vgmPlayChipCoreSelections: Map<String, Int>,
    openMptStereoSeparationPercent: Int,
    openMptStereoSeparationAmigaPercent: Int,
    openMptInterpolationFilterLength: Int,
    openMptAmigaResamplerMode: Int,
    openMptAmigaResamplerApplyAllModules: Boolean,
    openMptVolumeRampingStrength: Int,
    openMptFt2XmVolumeRamping: Boolean,
    openMptMasterGainMilliBel: Int,
    openMptSurroundEnabled: Boolean
): SettingsScreenState {
    return SettingsScreenState(
        selectedPluginName = selectedPluginName,
        autoPlayOnTrackSelect = autoPlayOnTrackSelect,
        openPlayerOnTrackSelect = openPlayerOnTrackSelect,
        autoPlayNextTrackOnEnd = autoPlayNextTrackOnEnd,
        previousRestartsAfterThreshold = previousRestartsAfterThreshold,
        respondHeadphoneMediaButtons = respondHeadphoneMediaButtons,
        pauseOnHeadphoneDisconnect = pauseOnHeadphoneDisconnect,
        audioFocusInterrupt = audioFocusInterrupt,
        audioDucking = audioDucking,
        audioBackendPreference = audioBackendPreference,
        audioPerformanceMode = audioPerformanceMode,
        audioBufferPreset = audioBufferPreset,
        audioResamplerPreference = audioResamplerPreference,
        audioAllowBackendFallback = audioAllowBackendFallback,
        openPlayerFromNotification = openPlayerFromNotification,
        persistRepeatMode = persistRepeatMode,
        themeMode = themeMode,
        rememberBrowserLocation = rememberBrowserLocation,
        recentFoldersLimit = recentFoldersLimit,
        recentFilesLimit = recentFilesLimit,
        urlCacheClearOnLaunch = urlCacheClearOnLaunch,
        urlCacheMaxTracks = urlCacheMaxTracks,
        urlCacheMaxBytes = urlCacheMaxBytes,
        cachedSourceFiles = cachedSourceFiles,
        keepScreenOn = keepScreenOn,
        playerArtworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing,
        unknownTrackDurationSeconds = unknownTrackDurationSeconds,
        endFadeApplyToAllTracks = endFadeApplyToAllTracks,
        endFadeDurationMs = endFadeDurationMs,
        endFadeCurve = endFadeCurve,
        visualizationMode = visualizationMode,
        enabledVisualizationModes = enabledVisualizationModes,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        ffmpegSampleRateHz = ffmpegSampleRateHz,
        ffmpegCapabilities = ffmpegCapabilities,
        openMptSampleRateHz = openMptSampleRateHz,
        openMptCapabilities = openMptCapabilities,
        vgmPlaySampleRateHz = vgmPlaySampleRateHz,
        vgmPlayCapabilities = vgmPlayCapabilities,
        gmeSampleRateHz = gmeSampleRateHz,
        sidPlayFpSampleRateHz = sidPlayFpSampleRateHz,
        lazyUsf2SampleRateHz = lazyUsf2SampleRateHz,
        lazyUsf2UseHleAudio = lazyUsf2UseHleAudio,
        sidPlayFpBackend = sidPlayFpBackend,
        sidPlayFpClockMode = sidPlayFpClockMode,
        sidPlayFpSidModelMode = sidPlayFpSidModelMode,
        sidPlayFpFilter6581Enabled = sidPlayFpFilter6581Enabled,
        sidPlayFpFilter8580Enabled = sidPlayFpFilter8580Enabled,
        sidPlayFpDigiBoost8580 = sidPlayFpDigiBoost8580,
        sidPlayFpFilterCurve6581Percent = sidPlayFpFilterCurve6581Percent,
        sidPlayFpFilterRange6581Percent = sidPlayFpFilterRange6581Percent,
        sidPlayFpFilterCurve8580Percent = sidPlayFpFilterCurve8580Percent,
        sidPlayFpReSidFpFastSampling = sidPlayFpReSidFpFastSampling,
        sidPlayFpReSidFpCombinedWaveformsStrength = sidPlayFpReSidFpCombinedWaveformsStrength,
        gmeTempoPercent = gmeTempoPercent,
        gmeStereoSeparationPercent = gmeStereoSeparationPercent,
        gmeEchoEnabled = gmeEchoEnabled,
        gmeAccuracyEnabled = gmeAccuracyEnabled,
        gmeEqTrebleDecibel = gmeEqTrebleDecibel,
        gmeEqBassHz = gmeEqBassHz,
        gmeSpcUseBuiltInFade = gmeSpcUseBuiltInFade,
        gmeSpcInterpolation = gmeSpcInterpolation,
        gmeSpcUseNativeSampleRate = gmeSpcUseNativeSampleRate,
        vgmPlayLoopCount = vgmPlayLoopCount,
        vgmPlayAllowNonLoopingLoop = vgmPlayAllowNonLoopingLoop,
        vgmPlayVsyncRate = vgmPlayVsyncRate,
        vgmPlayResampleMode = vgmPlayResampleMode,
        vgmPlayChipSampleMode = vgmPlayChipSampleMode,
        vgmPlayChipSampleRate = vgmPlayChipSampleRate,
        vgmPlayChipCoreSelections = vgmPlayChipCoreSelections,
        openMptStereoSeparationPercent = openMptStereoSeparationPercent,
        openMptStereoSeparationAmigaPercent = openMptStereoSeparationAmigaPercent,
        openMptInterpolationFilterLength = openMptInterpolationFilterLength,
        openMptAmigaResamplerMode = openMptAmigaResamplerMode,
        openMptAmigaResamplerApplyAllModules = openMptAmigaResamplerApplyAllModules,
        openMptVolumeRampingStrength = openMptVolumeRampingStrength,
        openMptFt2XmVolumeRamping = openMptFt2XmVolumeRamping,
        openMptMasterGainMilliBel = openMptMasterGainMilliBel,
        openMptSurroundEnabled = openMptSurroundEnabled
    )
}
